baseURL = "https://kykeon.church/"
locale = "en-us"
title = "Second Church of the Kykeon"
disableKinds = ["taxonomy", "term"]

[params]
  googleClientId = "427532768256-9qa939sou6cft90ji3egha9qe7s01l7m.apps.googleusercontent.com"
  turnstileSiteKey = "0x4AAAAAAFO-RBZK6xpHv_PX"

[menus]
  [[menus.main]]
    name = "Leadership"
    url = "/leadership/"
    weight = 30
  [[menus.main]]
    name = "Sacrament"
    url = "/sacrament/"
    weight = 20
  [[menus.main]]
    name = "Philosophy"
    url = "/philosophy/"
    weight = 5
  [[menus.main]]
    name = "Membership"
    url = "/membership/"
    weight = 8

[markup.goldmark.renderer]
  unsafe = true
